import { Project, User, Activity, Notification, Dispute, Quote } from "@/types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Adebayo Ogundimu",
    email: "adebayo@konstruct.ng",
    role: "owner",
    organization: "Ogundimu Holdings",
    phone: "+234 803 456 7890",
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "user-2",
    name: "Chidinma Eze",
    email: "chidinma@buildright.ng",
    role: "contractor",
    organization: "BuildRight Construction Ltd",
    phone: "+234 805 123 4567",
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "user-3",
    name: "Funke Adeyemi",
    email: "funke@designstudio.ng",
    role: "architect",
    organization: "Funke Adeyemi Design Studio",
    phone: "+234 807 987 6543",
    createdAt: "2025-02-10T10:00:00Z",
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "Maison Beaumont Estate",
    description: "A premium 5-bedroom detached duplex with boys quarter in Lekki Phase 1",
    location: "Lekki Phase 1, Lagos",
    address: "15 Admiralty Way, Lekki Phase 1, Lagos",
    projectType: "Residential",
    totalBudget: 120000000,
    spentBudget: 38000000,
    currency: "NGN",
    startDate: "2025-03-01",
    expectedEndDate: "2025-12-31",
    ownerId: "user-1",
    collaborators: ["user-2", "user-3"],
    createdAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-07-20T10:00:00Z",
    status: "in_progress",
    completionPercentage: 35,
    fundsLocked: 82000000,
    fundsReleased: 38000000,
    phases: [
      {
        id: "phase-1",
        projectId: "proj-1",
        title: "Foundation",
        description: "Excavation, concrete laying, foundation walls, and backfilling",
        order: 1,
        budgetAllocation: 25000000,
        budgetSpent: 23500000,
        status: "completed",
        milestones: [
          { id: "ms-1-1", title: "Site excavation completed", description: "Full excavation to required depth", completed: true, completedAt: "2025-03-15T14:00:00Z", completedBy: "user-2" },
          { id: "ms-1-2", title: "Concrete foundation poured", description: "All foundation concrete poured and cured", completed: true, completedAt: "2025-03-28T16:00:00Z", completedBy: "user-2" },
          { id: "ms-1-3", title: "Foundation walls completed", description: "Blockwork for foundation walls", completed: true, completedAt: "2025-04-10T12:00:00Z", completedBy: "user-2" },
          { id: "ms-1-4", title: "Backfilling and compaction", description: "Site backfilled and compacted", completed: true, completedAt: "2025-04-15T10:00:00Z", completedBy: "user-2" },
        ],
        evidence: [
          { id: "ev-1-1", phaseId: "phase-1", type: "photo", url: "/evidence/foundation-1.jpg", caption: "Excavation in progress", uploadedBy: "user-2", uploadedAt: "2025-03-12T10:00:00Z", verified: true, verifiedBy: "user-1", verifiedAt: "2025-03-13T10:00:00Z" },
          { id: "ev-1-2", phaseId: "phase-1", type: "photo", url: "/evidence/foundation-2.jpg", caption: "Concrete pouring", uploadedBy: "user-2", uploadedAt: "2025-03-25T10:00:00Z", verified: true, verifiedBy: "user-1", verifiedAt: "2025-03-26T10:00:00Z" },
        ],
        approvedBy: "user-1",
        approvedAt: "2025-04-20T10:00:00Z",
        completedAt: "2025-04-18T10:00:00Z",
        fundReleased: true,
        requiredDocuments: ["Foundation drawing", "Soil test report", "Concrete test results"],
      },
      {
        id: "phase-2",
        projectId: "proj-1",
        title: "Blockwork",
        description: "Wall construction, lintels, and floor slabs",
        order: 2,
        budgetAllocation: 35000000,
        budgetSpent: 14500000,
        status: "in_progress",
        milestones: [
          { id: "ms-2-1", title: "Ground floor walls completed", description: "All ground floor blockwork done", completed: true, completedAt: "2025-05-20T14:00:00Z", completedBy: "user-2" },
          { id: "ms-2-2", title: "First floor slab cast", description: "First floor concrete slab completed", completed: true, completedAt: "2025-06-05T16:00:00Z", completedBy: "user-2" },
          { id: "ms-2-3", title: "First floor walls completed", description: "All first floor blockwork done", completed: false },
          { id: "ms-2-4", title: "Lintel and beam casting", description: "All lintels and beams cast", completed: false },
        ],
        evidence: [
          { id: "ev-2-1", phaseId: "phase-2", type: "photo", url: "/evidence/blockwork-1.jpg", caption: "Ground floor walls taking shape", uploadedBy: "user-2", uploadedAt: "2025-05-15T10:00:00Z", verified: true, verifiedBy: "user-1", verifiedAt: "2025-05-16T10:00:00Z" },
        ],
        submittedBy: "user-2",
        submittedAt: "2025-06-10T10:00:00Z",
        fundReleased: false,
        requiredDocuments: ["Structural drawing", "Block test results", "Supervisor report"],
      },
      {
        id: "phase-3",
        projectId: "proj-1",
        title: "Roofing",
        description: "Roof trusses, decking, and roofing sheets installation",
        order: 3,
        budgetAllocation: 20000000,
        budgetSpent: 0,
        status: "not_started",
        milestones: [
          { id: "ms-3-1", title: "Roof trusses installed", description: "All timber or steel trusses fixed", completed: false },
          { id: "ms-3-2", title: "Roofing sheets fixed", description: "All roofing sheets installed", completed: false },
          { id: "ms-3-3", title: "Ceiling installed", description: "Ceiling framework and boards fixed", completed: false },
        ],
        evidence: [],
        fundReleased: false,
        requiredDocuments: ["Roofing plan", "Material delivery receipts"],
      },
      {
        id: "phase-4",
        projectId: "proj-1",
        title: "Finishing",
        description: "Plastering, tiling, painting, plumbing, and electrical works",
        order: 4,
        budgetAllocation: 30000000,
        budgetSpent: 0,
        status: "not_started",
        milestones: [
          { id: "ms-4-1", title: "Plastering completed", description: "All walls plastered", completed: false },
          { id: "ms-4-2", title: "Tiling completed", description: "All floor and wall tiles fixed", completed: false },
          { id: "ms-4-3", title: "Painting completed", description: "All surfaces painted", completed: false },
          { id: "ms-4-4", title: "Plumbing fixed", description: "All plumbing fixtures installed", completed: false },
          { id: "ms-4-5", title: "Electrical fixed", description: "All wiring and fittings completed", completed: false },
        ],
        evidence: [],
        fundReleased: false,
        requiredDocuments: ["MEP drawings", "Material samples", "Electrical test certificate"],
      },
      {
        id: "phase-5",
        projectId: "proj-1",
        title: "External Works",
        description: "Perimeter fencing, gate house, landscaping, and drainage",
        order: 5,
        budgetAllocation: 10000000,
        budgetSpent: 0,
        status: "not_started",
        milestones: [
          { id: "ms-5-1", title: "Perimeter fencing completed", description: "All fence walls built", completed: false },
          { id: "ms-5-2", title: "Gate house completed", description: "Gate house structure and finishes", completed: false },
          { id: "ms-5-3", title: "Landscaping completed", description: "All landscaping works done", completed: false },
          { id: "ms-5-4", title: "Drainage completed", description: "All drainage channels and soakaway done", completed: false },
        ],
        evidence: [],
        fundReleased: false,
        requiredDocuments: ["Site plan", "Drainage plan"],
      },
    ],
  },
  {
    id: "proj-2",
    name: "Tropical Gardens Mall",
    description: "A 3-floor commercial shopping complex in Ikeja",
    location: "Ikeja, Lagos",
    address: "22 Allen Avenue, Ikeja, Lagos",
    projectType: "Commercial",
    totalBudget: 450000000,
    spentBudget: 90000000,
    currency: "NGN",
    startDate: "2025-01-15",
    expectedEndDate: "2026-03-31",
    ownerId: "user-1",
    collaborators: ["user-2", "user-3"],
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-07-18T10:00:00Z",
    status: "in_progress",
    completionPercentage: 20,
    fundsLocked: 360000000,
    fundsReleased: 90000000,
    phases: [
      {
        id: "phase-6",
        projectId: "proj-2",
        title: "Foundation",
        description: "Piling and foundation construction",
        order: 1,
        budgetAllocation: 90000000,
        budgetSpent: 90000000,
        status: "completed",
        milestones: [
          { id: "ms-6-1", title: "Piling completed", description: "All piles driven and tested", completed: true, completedAt: "2025-02-28T14:00:00Z", completedBy: "user-2" },
          { id: "ms-6-2", title: "Pile caps cast", description: "All pile caps completed", completed: true, completedAt: "2025-03-20T16:00:00Z", completedBy: "user-2" },
          { id: "ms-6-3", title: "Ground beams completed", description: "Ground beams cast and cured", completed: true, completedAt: "2025-04-15T12:00:00Z", completedBy: "user-2" },
        ],
        evidence: [],
        approvedBy: "user-1",
        approvedAt: "2025-04-20T10:00:00Z",
        completedAt: "2025-04-18T10:00:00Z",
        fundReleased: true,
        requiredDocuments: ["Piling log", "Load test results"],
      },
      {
        id: "phase-7",
        projectId: "proj-2",
        title: "Structural Frame",
        description: "Columns, beams, and floor slabs for all floors",
        order: 2,
        budgetAllocation: 120000000,
        budgetSpent: 0,
        status: "not_started",
        milestones: [
          { id: "ms-7-1", title: "Ground floor columns and beams", description: "Ground floor structural frame", completed: false },
          { id: "ms-7-2", title: "First floor slab cast", description: "First floor concrete slab", completed: false },
          { id: "ms-7-3", title: "Second floor slab cast", description: "Second floor concrete slab", completed: false },
        ],
        evidence: [],
        fundReleased: false,
        requiredDocuments: ["Structural drawings", "Concrete mix design"],
      },
    ],
  },
];

export const mockActivities: Activity[] = [
  { id: "act-1", projectId: "proj-1", userId: "user-2", userName: "Chidinma Eze", action: "Submitted evidence", details: "Uploaded 3 photos for Blockwork phase - First floor walls", timestamp: "2025-07-20T14:30:00Z", type: "evidence" },
  { id: "act-2", projectId: "proj-1", userId: "user-1", userName: "Adebayo Ogundimu", action: "Approved milestone", details: "Approved First floor slab cast milestone in Blockwork", timestamp: "2025-07-19T10:15:00Z", type: "phase" },
  { id: "act-3", projectId: "proj-1", userId: "user-3", userName: "Funke Adeyemi", action: "Added comment", details: "Roofing material selection needs review before Phase 3 starts", timestamp: "2025-07-18T16:45:00Z", type: "comment" },
  { id: "act-4", projectId: "proj-1", userId: "user-2", userName: "Chidinma Eze", action: "Requested payment", details: "Payment request for Blockwork phase - ₦14,500,000", timestamp: "2025-07-17T09:00:00Z", type: "payment" },
  { id: "act-5", projectId: "proj-1", userId: "user-1", userName: "Adebayo Ogundimu", action: "Approved payment", details: "Released ₦25,000,000 for Foundation phase completion", timestamp: "2025-07-15T11:00:00Z", type: "payment" },
  { id: "act-6", projectId: "proj-1", userId: "system", userName: "System", action: "Phase completed", details: "Foundation phase marked as completed", timestamp: "2025-07-10T10:00:00Z", type: "system" },
  { id: "act-7", projectId: "proj-2", userId: "user-2", userName: "Chidinma Eze", action: "Phase started", details: "Started Structural Frame phase for Tropical Gardens Mall", timestamp: "2025-07-16T08:00:00Z", type: "phase" },
];

export const mockNotifications: Notification[] = [
  { id: "notif-1", userId: "user-1", title: "Evidence submitted", message: "Chidinma submitted 3 photos for Blockwork phase", type: "evidence", read: false, createdAt: "2025-07-20T14:30:00Z", projectId: "proj-1" },
  { id: "notif-2", userId: "user-1", title: "Payment request", message: "Payment request of ₦14,500,000 pending approval", type: "payment", read: false, createdAt: "2025-07-17T09:00:00Z", projectId: "proj-1" },
  { id: "notif-3", userId: "user-2", title: "Milestone approved", message: "Adebayo approved First floor slab cast milestone", type: "approval", read: true, createdAt: "2025-07-19T10:15:00Z", projectId: "proj-1" },
  { id: "notif-4", userId: "user-1", title: "New comment", message: "Funke commented on roofing material selection", type: "system", read: true, createdAt: "2025-07-18T16:45:00Z", projectId: "proj-1" },
];

export const mockDisputes: Dispute[] = [
  {
    id: "disp-1",
    projectId: "proj-1",
    phaseId: "phase-2",
    title: "Concrete mix quality concern",
    description: "The concrete mix ratio used for the first floor slab appears weaker than specification. Request independent testing.",
    raisedBy: "user-1",
    status: "in_review",
    createdAt: "2025-07-15T10:00:00Z",
    messages: [
      { id: "dm-1", userId: "user-1", content: "The concrete looks pale. Can you provide the mix design certificate?", createdAt: "2025-07-15T10:00:00Z" },
      { id: "dm-2", userId: "user-2", content: "We used 1:2:4 as specified. Here is the batcher's ticket and mix design.", createdAt: "2025-07-15T14:00:00Z" },
      { id: "dm-3", userId: "user-1", content: "Thank you. I will arrange an independent test next week.", createdAt: "2025-07-16T09:00:00Z" },
    ],
  },
];

export const mockQuotes: Quote[] = [
  {
    id: "quote-1",
    projectId: "proj-1",
    contractorId: "user-2",
    contractorName: "BuildRight Construction Ltd",
    totalAmount: 20000000,
    items: [
      { id: "qi-1", description: "Roof trusses (treated timber)", quantity: 45, unit: "pieces", unitPrice: 250000, total: 11250000 },
      { id: "qi-2", description: "Roofing sheets (Stone-coated)", quantity: 120, unit: "sheets", unitPrice: 45000, total: 5400000 },
      { id: "qi-3", description: "Ceiling boards", quantity: 80, unit: "sheets", unitPrice: 41875, total: 3350000 },
    ],
    status: "pending",
    submittedAt: "2025-07-10T10:00:00Z",
  },
];
