import { jsPDF } from "jspdf";
import type { Project } from "@/types";
import { formatNaira } from "@/lib/utils";

export function exportProjectReport(project: Project): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Project Report", pageWidth / 2, y, { align: "center" });
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" })}`, pageWidth / 2, y, { align: "center" });
  y += 15;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(project.name, 20, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Location: ${project.location || "N/A"}`, 20, y); y += 6;
  doc.text(`Type: ${project.projectType}`, 20, y); y += 6;
  doc.text(`Status: ${project.status}`, 20, y); y += 6;
  doc.text(`Start Date: ${project.startDate || "N/A"}`, 20, y); y += 6;
  doc.text(`Expected End: ${project.expectedEndDate || "N/A"}`, 20, y); y += 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Budget Summary", 20, y); y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Total Budget: ${formatNaira(project.totalBudget)}`, 20, y); y += 6;
  doc.text(`Spent: ${formatNaira(project.spentBudget)}`, 20, y); y += 6;
  doc.text(`Funds Locked: ${formatNaira(project.fundsLocked)}`, 20, y); y += 6;
  doc.text(`Funds Released: ${formatNaira(project.fundsReleased)}`, 20, y); y += 6;
  doc.text(`Completion: ${project.completionPercentage}%`, 20, y); y += 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Phases", 20, y); y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  project.phases.forEach((phase, i) => {
    if (y > 260) { doc.addPage(); y = 20; }
    const done = phase.milestones.filter((m) => m.completed).length;
    doc.text(`${i + 1}. ${phase.title}`, 20, y); y += 5;
    doc.text(`   Status: ${phase.status} | Budget: ${formatNaira(phase.budgetAllocation)} | Milestones: ${done}/${phase.milestones.length}`, 20, y); y += 7;
  });

  y += 5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Evidence Summary", 20, y); y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const allEvidence = project.phases.flatMap((p) => p.evidence);
  const photos = allEvidence.filter((e) => e.type === "photo").length;
  const videos = allEvidence.filter((e) => e.type === "video").length;
  const docs = allEvidence.filter((e) => e.type === "document").length;
  const verified = allEvidence.filter((e) => e.verified).length;
  doc.text(`Total Evidence: ${allEvidence.length}`, 20, y); y += 5;
  doc.text(`Photos: ${photos} | Videos: ${videos} | Documents: ${docs}`, 20, y); y += 5;
  doc.text(`Verified: ${verified}/${allEvidence.length}`, 20, y); y += 12;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by Konstruct — The trust engine for construction delivery in Nigeria", pageWidth / 2, 285, { align: "center" });

  doc.save(`${project.name.replace(/[^a-zA-Z0-9]/g, "_")}_report.pdf`);
}
